version: '3.0'

services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    hostname: mtproxy
    container_name: mtproxy.local
    environment:
      - SECRET=${SECRET}
    volumes:
      - proxy-config:/data
      - ./run.sh:/run.sh:ro
    ports:
      - "4487:443"
    logging:
      driver: syslog
      options:
        tag: mtproxy
    restart: unless-stopped

volumes:
  proxy-config: