services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./conf.d/botblocker-nginx-settings.conf:/etc/nginx/conf.d/botblocker-nginx-settings.conf
      - ./conf.d/globalblacklist.conf:/etc/nginx/conf.d/globalblacklist.conf
      - ./bots.d:/etc/nginx/bots.d
